# name of the GitHub action
name: linting

# trigger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Python Setup
        uses: actions/setup-python@v6.2.0
        with:
           python-version: ${{secrets.PYTHON_VERSION}}

      - name: Checking Python Version
        run: python --version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
           
      
  

  





